### ISSUE TITLE
npm install typo

### ISSUE THREAD

**Issue by Alex61NN5** [polakdominik/ngx-cropperjs-wrapper#2]
Hey there,

In your README.md you say to install the package like so

`npm install ngx-cropper-js-wrapper`

but there is a typo, running this will result in an npm error

it should be updated to 

`npm install ngx-cropperjs-wrapper`

**Comment by helthbrazil** [comment]
Hi. I set the 'rotatable' value equals true (in CropperOptions) and then i try to rotate the image but don't work. Can you help me?

**Comment by polakdominik** [comment]
@Alex61NN5 Thanks for the info. Fixed the README.
